name: Pipeline CI/CD MLOps

on: 
  pull_request:
    branches: [ dev ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: SetUp Python
        uses: actions/checkout@v5
        with:
          python-version: '3.12.7'

      - name: Install requirements
        run: pip install -r ./python/credit_scoring/requirements.txt}

      - name: Run tests
        run: pytest tests/test_model_creation.py -v
      
    
    
  
